import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderSection from "./header/page";
const inter = Inter({ 
  subsets: ["latin"],
  weight: ['400', '500', '600'],
  variable: '--inter'
});

export const metadata: Metadata = {
  title: "Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout-container">
          <HeaderSection />
          <main className="main-content">{children}</main>
        </div>
      </body>
    </html>
  );
}
